#pragma once

// N3/N2 vocabulary, one per day (cycles). Keep usage sentences short —
// they must fit two lines on screen.
struct WotdEntry {
  const char* word;      // kanji
  const char* reading;   // hiragana
  const char* meaning;   // English
  const char* usage;     // Japanese example
  const char* usage_en;  // English translation
};

static const WotdEntry WOTD[] = {
  { "遠慮", "えんりょ", "restraint / holding back",
    "どうぞ遠慮なく食べてください。", "Please eat without holding back." },
  { "我慢", "がまん", "patience / endurance",
    "痛みを我慢して最後まで走った。", "I endured the pain and ran to the end." },
  { "迷惑", "めいわく", "nuisance / trouble",
    "人に迷惑をかけないでください。", "Please don't cause trouble for others." },
  { "都合", "つごう", "convenience / circumstances",
    "明日は都合が悪いです。", "Tomorrow doesn't work for me." },
  { "締め切り", "しめきり", "deadline",
    "レポートの締め切りは金曜日です。", "The report deadline is Friday." },
  { "打ち合わせ", "うちあわせ", "(work) meeting",
    "三時から打ち合わせがあります。", "I have a meeting from three o'clock." },
  { "手続き", "てつづき", "procedure / paperwork",
    "ビザの手続きに時間がかかった。", "The visa paperwork took a long time." },
  { "確認", "かくにん", "confirmation / checking",
    "予約を確認してください。", "Please confirm the reservation." },
  { "対応", "たいおう", "handling / response",
    "すぐに対応します。", "I will handle it right away." },
  { "募集", "ぼしゅう", "recruitment",
    "アルバイトを募集しています。", "They are recruiting part-time workers." },
  { "遅刻", "ちこく", "being late",
    "電車が遅れて遅刻した。", "The train was delayed and I was late." },
  { "残業", "ざんぎょう", "overtime work",
    "今日は残業しなければならない。", "I have to work overtime today." },
  { "貯金", "ちょきん", "savings",
    "旅行のために貯金している。", "I'm saving money for a trip." },
  { "引っ越し", "ひっこし", "moving house",
    "来月引っ越しをします。", "I'm moving next month." },
  { "割引", "わりびき", "discount",
    "学生は二割引になります。", "Students get a 20% discount." },
  { "渋滞", "じゅうたい", "traffic jam",
    "道が渋滞していて遅れた。", "The road was jammed, so I was late." },
  { "予防", "よぼう", "prevention",
    "手洗いは風邪の予防になる。", "Washing hands helps prevent colds." },
  { "節約", "せつやく", "saving / economizing",
    "電気を節約しましょう。", "Let's save electricity." },
  { "検討", "けんとう", "consideration / review",
    "その案を検討します。", "We will consider that proposal." },
  { "承知", "しょうち", "acknowledgment / consent",
    "承知しました。", "Understood. (polite)" },
  { "依頼", "いらい", "request / commission",
    "翻訳を依頼した。", "I requested a translation." },
  { "期限", "きげん", "time limit / expiry",
    "支払いの期限は明日です。", "The payment is due tomorrow." },
  { "故障", "こしょう", "breakdown / malfunction",
    "エレベーターが故障している。", "The elevator is out of order." },
  { "満員", "まんいん", "full (of people)",
    "朝の電車はいつも満員だ。", "The morning train is always packed." },
  { "苦手", "にがて", "bad at / dislike",
    "私は早起きが苦手です。", "I'm not good at getting up early." },
  { "得意", "とくい", "good at",
    "彼は料理が得意だ。", "He is good at cooking." },
  { "詳しい", "くわしい", "detailed / knowledgeable",
    "彼はパソコンに詳しい。", "He knows a lot about computers." },
  { "珍しい", "めずらしい", "rare / unusual",
    "今日は珍しく早く起きた。", "Unusually, I woke up early today." },
  { "面倒", "めんどう", "troublesome / a hassle",
    "手続きが面倒だ。", "The paperwork is a hassle." },
  { "大家", "おおや", "landlord",
    "大家さんに家賃を払った。", "I paid the rent to the landlord." },
  { "敬語", "けいご", "honorific language",
    "上司には敬語を使う。", "I use honorific language with my boss." },
  { "湿気", "しっけ", "humidity / moisture",
    "梅雨は湿気が多い。", "The rainy season is very humid." },
  { "停電", "ていでん", "power outage",
    "台風で停電した。", "The typhoon caused a power outage." },
  { "給料", "きゅうりょう", "salary",
    "給料日は二十五日です。", "Payday is the 25th." },
  { "通勤", "つうきん", "commuting",
    "通勤に一時間かかる。", "My commute takes one hour." },
  { "気温", "きおん", "(air) temperature",
    "今日の気温は三十度です。", "Today's temperature is 30 degrees." },
  { "台風", "たいふう", "typhoon",
    "台風が近づいている。", "A typhoon is approaching." },
  { "忘れ物", "わすれもの", "forgotten item",
    "電車に忘れ物をした。", "I left something on the train." },
  { "相談", "そうだん", "consultation / advice",
    "先生に相談した方がいい。", "You should talk to the teacher about it." },
  { "約束", "やくそく", "promise / appointment",
    "友達と会う約束がある。", "I have plans to meet a friend." },
};

static const int WOTD_COUNT = sizeof(WOTD) / sizeof(WOTD[0]);
